### ISSUE TITLE
Fails to build on Ubuntu 22.04

### ISSUE THREAD

**Issue by AndrewFasano** [panda-re/libosi#8]
Trying to bump PANDA's CI to use 22.04 (https://github.com/panda-re/panda/pull/1198) and it looks like libOSI won't build, here are the first few errors. I might try fixing them myself
```
[5/29] Building CXX object CMakeFiles/osi-obj.dir/src/osi/windows/mem_pe/mem_pe.cc.o
FAILED: CMakeFiles/osi-obj.dir/src/osi/windows/mem_pe/mem_pe.cc.o
/usr/bin/c++  -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/home/andrew/git/libosi/include -fPIC -std=c++14 -MD -MT CMakeFiles/osi-obj.dir/src/osi/windows/mem_pe/mem_pe.cc.o -MF CMakeFiles/osi-obj.dir/src/osi/windows/mem_pe/mem_pe.cc.o.d -o CMakeFiles/osi-obj.dir/src/osi/windows/mem_pe/mem_pe.cc.o -c /home/andrew/git/libosi/src/osi/wind
ows/mem_pe/mem_pe.cc
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc: In function ‘mem_pe* init_mem_pe(WindowsProcessOSI*, uint64_t, bool)’:
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:29:39: error: ‘calloc’ is not a member of ‘std’
   29 |     auto mempe = (struct mem_pe*)std::calloc(1, sizeof(struct mem_pe));
      |                                       ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:35:17: error: ‘stderr’ was not declared in this scope
   35 |         fprintf(stderr, "DOS Header is paged out %lx\n", image_base);
      |                 ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:6:1: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
    5 | #include "osi/windows/pe.h"
  +++ |+#include <cstdio>
    6 | #include "osi/windows/wintrospection.h"
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:35:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   35 |         fprintf(stderr, "DOS Header is paged out %lx\n", image_base);
      |         ^~~~~~~
      |         wprintf
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:36:14: error: ‘free’ is not a member of ‘std’
   36 |         std::free(mempe);
      |              ^~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:42:17: error: ‘stderr’ was not declared in this scope
   42 |         fprintf(stderr, "_IMAGE_DOS_HEADER.e_magic = %x\n", mempe->dos_header.e_magic);
      |                 ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:42:17: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:42:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   42 |         fprintf(stderr, "_IMAGE_DOS_HEADER.e_magic = %x\n", mempe->dos_header.e_magic);
      |         ^~~~~~~
      |         wprintf
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:43:14: error: ‘free’ is not a member of ‘std’
   43 |         std::free(mempe);
      |              ^~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:51:17: error: ‘stderr’ was not declared in this scope
   51 |         fprintf(stderr, "Failed to read nt header at %lx\n", nt_header_address);
      |                 ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:51:17: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:51:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   51 |         fprintf(stderr, "Failed to read nt header at %lx\n", nt_header_address);
      |         ^~~~~~~
      |         wprintf
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:52:14: error: ‘free’ is not a member of ‘std’
   52 |         std::free(mempe);
      |              ^~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:57:17: error: ‘stderr’ was not declared in this scope
   57 |         fprintf(stderr, "_IMAGE_NT_HEADERS.Signature = %x\n", mempe->dos_header.e_magic);
      |                 ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:57:17: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:57:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   57 |         fprintf(stderr, "_IMAGE_NT_HEADERS.Signature = %x\n", mempe->dos_header.e_magic);
      |         ^~~~~~~
      |         wprintf
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:58:14: error: ‘free’ is not a member of ‘std’
   58 |         std::free(mempe);
      |              ^~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:73:17: error: ‘stderr’ was not declared in this scope
   73 |         fprintf(stderr, "Failed to read optional header at %lx\n", optional_header);
      |                 ^~~~~~
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:73:17: note: ‘stderr’ is defined in header ‘<cstdio>’; did you forget to ‘#include <cstdio>’?
/home/andrew/git/libosi/src/osi/windows/mem_pe/mem_pe.cc:73:9: error: ‘fprintf’ was not declared in this scope; did you mean ‘wprintf’?
   73 |         fprintf(stderr, "Failed to read optional header at %lx\n", optional_header);
      |         ^~~~~~~
      |         wprintf
```
